<?php
/**
 * SignProgramMultisigRequest.
 *
 * PHP version 7.3
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * for KMD HTTP API.
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rootsoft\Algorand\KMD\Model;

use ArrayAccess;
use Rootsoft\Algorand\KMD\ObjectSerializer;

/**
 * SignProgramMultisigRequest Class Doc Comment.
 *
 * @category Class
 * @description APIV1POSTMultisigProgramSignRequest is the request for &#x60;POST /v1/multisig/signprogram&#x60;
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SignProgramMultisigRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SignProgramMultisigRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'address' => 'string',
        'data' => 'string',
        'partial_multisig' => '\Rootsoft\Algorand\KMD\Model\MultisigSig',
        'public_key' => 'int[]',
        'wallet_handle_token' => 'string',
        'wallet_password' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'address' => null,
        'data' => 'byte',
        'partial_multisig' => null,
        'public_key' => 'uint8',
        'wallet_handle_token' => null,
        'wallet_password' => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'data' => 'data',
        'partial_multisig' => 'partial_multisig',
        'public_key' => 'public_key',
        'wallet_handle_token' => 'wallet_handle_token',
        'wallet_password' => 'wallet_password',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'data' => 'setData',
        'partial_multisig' => 'setPartialMultisig',
        'public_key' => 'setPublicKey',
        'wallet_handle_token' => 'setWalletHandleToken',
        'wallet_password' => 'setWalletPassword',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'data' => 'getData',
        'partial_multisig' => 'getPartialMultisig',
        'public_key' => 'getPublicKey',
        'wallet_handle_token' => 'getWalletHandleToken',
        'wallet_password' => 'getWalletPassword',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = $data['address'] ?? null;
        $this->container['data'] = $data['data'] ?? null;
        $this->container['partial_multisig'] = $data['partial_multisig'] ?? null;
        $this->container['public_key'] = $data['public_key'] ?? null;
        $this->container['wallet_handle_token'] = $data['wallet_handle_token'] ?? null;
        $this->container['wallet_password'] = $data['wallet_password'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (! is_null($this->container['data']) && ! preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['data'])) {
            $invalidProperties[] = "invalid value for 'data', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets address.
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address.
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets data.
     *
     * @return string|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data.
     *
     * @param string|null $data data
     *
     * @return self
     */
    public function setData($data)
    {
        if (! is_null($data) && (! preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $data))) {
            throw new \InvalidArgumentException("invalid value for $data when calling SignProgramMultisigRequest., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets partial_multisig.
     *
     * @return \Rootsoft\Algorand\KMD\Model\MultisigSig|null
     */
    public function getPartialMultisig()
    {
        return $this->container['partial_multisig'];
    }

    /**
     * Sets partial_multisig.
     *
     * @param \Rootsoft\Algorand\KMD\Model\MultisigSig|null $partial_multisig partial_multisig
     *
     * @return self
     */
    public function setPartialMultisig($partial_multisig)
    {
        $this->container['partial_multisig'] = $partial_multisig;

        return $this;
    }

    /**
     * Gets public_key.
     *
     * @return int[]|null
     */
    public function getPublicKey()
    {
        return $this->container['public_key'];
    }

    /**
     * Sets public_key.
     *
     * @param int[]|null $public_key public_key
     *
     * @return self
     */
    public function setPublicKey($public_key)
    {
        $this->container['public_key'] = $public_key;

        return $this;
    }

    /**
     * Gets wallet_handle_token.
     *
     * @return string|null
     */
    public function getWalletHandleToken()
    {
        return $this->container['wallet_handle_token'];
    }

    /**
     * Sets wallet_handle_token.
     *
     * @param string|null $wallet_handle_token wallet_handle_token
     *
     * @return self
     */
    public function setWalletHandleToken($wallet_handle_token)
    {
        $this->container['wallet_handle_token'] = $wallet_handle_token;

        return $this;
    }

    /**
     * Gets wallet_password.
     *
     * @return string|null
     */
    public function getWalletPassword()
    {
        return $this->container['wallet_password'];
    }

    /**
     * Sets wallet_password.
     *
     * @param string|null $wallet_password wallet_password
     *
     * @return self
     */
    public function setWalletPassword($wallet_password)
    {
        $this->container['wallet_password'] = $wallet_password;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
